# Generated by Django 4.2 on 2023-05-21 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='boolean_question',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='numerical_option',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='question_type',
            field=models.CharField(choices=[('numerical', 'numerical'), ('Boolean', 'Boolean'), ('mcq', 'mcq')], default='mcq', max_length=10),
        ),
        migrations.AlterField(
            model_name='marks',
            name='negative_marking',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='positive_marking',
            field=models.IntegerField(blank=True, default=4, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='question_marking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marking', to='room.questions'),
        ),
        migrations.CreateModel(
            name='TakenQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taken_quizzes', to='room.quizzes')),
                ('quiztaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taken_quizzes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Quiztaker',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='quiztaker', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('quizzes', models.ManyToManyField(to='room.quizzes')),
            ],
        ),
        migrations.CreateModel(
            name='QTAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='room.answer')),
                ('quiztaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_answers', to='room.quiztaker')),
            ],
        ),
    ]
