# Generated by Django 4.2 on 2023-05-07 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='negative_marking',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='marks',
            name='positive_marking',
            field=models.IntegerField(default=4),
        ),
    ]
