# Generated by Django 4.2 on 2023-05-07 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_alter_marks_negative_marking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='negative_marking',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='marks',
            name='positive_marking',
            field=models.IntegerField(blank=True, default=4),
        ),
    ]
