# Generated by Django 4.2 on 2023-05-07 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_alter_marks_negative_marking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='question_marking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marking', to='room.questions'),
        ),
    ]
