# Generated by Django 4.2 on 2023-05-07 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_alter_marks_question_marking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='negative_marking',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='positive_marking',
            field=models.IntegerField(blank=True, default=4, null=True),
        ),
    ]
