# Generated by Django 4.2 on 2023-05-07 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0006_takenquiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role_choice',
        ),
    ]
