# Generated by Django 4.2 on 2023-05-09 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0008_answer_boolean_question_answer_numerical_option_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='question_type',
            field=models.CharField(choices=[('numerical', 'numerical'), ('Boolean', 'Boolean'), ('mcq', 'mcq')], default='mcq', max_length=10, null=True),
        ),
    ]
