# Generated by Django 4.2 on 2023-05-09 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0009_alter_questions_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='question_type',
            field=models.CharField(choices=[('numerical', 'numerical'), ('Boolean', 'Boolean'), ('mcq', 'mcq')], default='mcq', max_length=10),
        ),
    ]
