# Generated by Django 4.2 on 2023-05-13 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0011_user_role_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiztaker',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('quizzes', models.ManyToManyField(to='room.quizzes')),
            ],
        ),
        migrations.CreateModel(
            name='QTAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='room.answer')),
                ('quiztaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_answers', to='room.quiztaker')),
            ],
        ),
    ]
