# Generated by Django 4.2 on 2023-05-13 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0012_quiztaker_qtanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiztaker',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='quiztaker', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
