# Generated by Django 4.2 on 2023-05-27 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_answer_boolean_question_answer_numerical_option_and_more'),
        ('room', '0013_alter_quiztaker_user'),
    ]

    operations = [
    ]
